Issue #33: WIP attempt at loading JSON into Sass but not compiling:
Causes many errors:

NoSuchMethodError: method not found: 'apply' (importer.apply is not a function)